#!/usr/bin/env python3
"""Generate and validate canonical Merkle proof vectors for the CKB benchmark.

The benchmark models 13 committed execution states.  Each state is represented
by an already-hashed 32-byte digest.  The tree is padded to 16 leaves using the
all-zero 32-byte digest.  Internal nodes use CKB's default Blake2b-256:
digest_size=32, personalization=b"ckb-default-hash".

Proof siblings are precomputed so the measured Rust verification path performs
exactly one parent hash per authentication level.  It does not spend benchmark
cycles fabricating sibling hashes.
"""
from __future__ import annotations

import argparse
import hashlib
from pathlib import Path

LEAF_COUNT = 13
PADDED_LEAF_COUNT = 16
DEPTH = 4
PERSONALIZATION = b"ckb-default-hash"


def ckb_hash(data: bytes) -> bytes:
    return hashlib.blake2b(
        data, digest_size=32, person=PERSONALIZATION
    ).digest()


def canonical_leaves() -> list[bytes]:
    # The first 13 values stand for already-committed state digests.
    leaves = [bytes([i + 1]) * 32 for i in range(LEAF_COUNT)]
    leaves.extend([bytes(32)] * (PADDED_LEAF_COUNT - LEAF_COUNT))
    return leaves


def build_levels(leaves: list[bytes]) -> list[list[bytes]]:
    if len(leaves) != PADDED_LEAF_COUNT:
        raise ValueError(f"expected {PADDED_LEAF_COUNT} padded leaves")
    levels = [list(leaves)]
    while len(levels[-1]) > 1:
        previous = levels[-1]
        if len(previous) % 2:
            raise ValueError("each Merkle level must have an even node count")
        levels.append(
            [
                ckb_hash(previous[i] + previous[i + 1])
                for i in range(0, len(previous), 2)
            ]
        )
    return levels


def proof_for(levels: list[list[bytes]], leaf_index: int) -> list[bytes]:
    if not 0 <= leaf_index < LEAF_COUNT:
        raise ValueError(f"leaf_index must be in 0..{LEAF_COUNT - 1}")
    proof: list[bytes] = []
    pos = leaf_index
    for level in range(DEPTH):
        proof.append(levels[level][pos ^ 1])
        pos //= 2
    return proof


def verify_proof(leaf: bytes, leaf_index: int, siblings: list[bytes]) -> bytes:
    if len(leaf) != 32 or any(len(s) != 32 for s in siblings):
        raise ValueError("leaf and siblings must be 32-byte digests")
    current = leaf
    for level, sibling in enumerate(siblings):
        if ((leaf_index >> level) & 1) == 0:
            current = ckb_hash(current + sibling)
        else:
            current = ckb_hash(sibling + current)
    return current


def _rust_array(value: bytes) -> str:
    return "[" + ", ".join(f"0x{b:02x}" for b in value) + "]"


def render_rust() -> str:
    leaves = canonical_leaves()
    levels = build_levels(leaves)
    root = levels[-1][0]
    proofs = [proof_for(levels, i) for i in range(LEAF_COUNT)]

    # These generic siblings are already supplied digests, not values hashed
    # inside the benchmark.  They are used only for the depth-scaling sweep at
    # depths other than the canonical depth-4 experiment.
    generic = [
        bytes(((level * 37 + i * 11 + 19) % 256 for i in range(32)))
        for level in range(8)
    ]

    lines = [
        "// Generated by ../generate_merkle_vectors.py; do not edit by hand.",
        "// Canonical tree: 13 committed-state hashes, padded to 16 leaves with zero hashes.",
        f"pub const CANONICAL_LEAF_COUNT: usize = {LEAF_COUNT};",
        f"pub const CANONICAL_DEPTH: usize = {DEPTH};",
        f"pub const CANONICAL_ROOT: [u8; 32] = {_rust_array(root)};",
        "pub const CANONICAL_LEAVES: [[u8; 32]; CANONICAL_LEAF_COUNT] = [",
    ]
    lines.extend(f"    {_rust_array(v)}," for v in leaves[:LEAF_COUNT])
    lines.extend(
        [
            "];",
            "pub const CANONICAL_PROOFS: [[[u8; 32]; CANONICAL_DEPTH]; CANONICAL_LEAF_COUNT] = [",
        ]
    )
    for proof in proofs:
        lines.append("    [")
        lines.extend(f"        {_rust_array(v)}," for v in proof)
        lines.append("    ],")
    lines.extend(
        [
            "];",
            "pub const GENERIC_SIBLINGS: [[u8; 32]; 8] = [",
        ]
    )
    lines.extend(f"    {_rust_array(v)}," for v in generic)
    lines.append("];")
    return "\n".join(lines) + "\n"


def self_check() -> str:
    leaves = canonical_leaves()
    levels = build_levels(leaves)
    expected = levels[-1][0]
    for index in range(LEAF_COUNT):
        actual = verify_proof(leaves[index], index, proof_for(levels, index))
        if actual != expected:
            raise AssertionError(f"proof failed for canonical leaf {index}")
    return expected.hex()


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--output",
        default=str(Path(__file__).resolve().parent / "src" / "merkle_vectors.rs"),
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Validate all 13 canonical proofs and verify generated source is current.",
    )
    args = parser.parse_args()

    root_hex = self_check()
    output = Path(args.output)
    generated = render_rust()

    if args.check:
        if not output.exists():
            raise SystemExit(f"missing generated file: {output}")
        if output.read_text(encoding="utf-8") != generated:
            raise SystemExit(
                "generated Merkle vectors are stale; run "
                "`python ckb_bench/generate_merkle_vectors.py`"
            )
        print(f"Merkle vectors OK: 13/13 proofs, root={root_hex}")
        return

    output.write_text(generated, encoding="utf-8")
    print(f"Wrote {output}")
    print(f"Canonical root: {root_hex}")


if __name__ == "__main__":
    main()
